/**
 * Generated by https://quicktype.io
 */

export interface IProduct {
  onlineProdSn: number;
  onlineProdCode?: string;
  onlineProdName: string;
  lineDesc?: string;
  brandSn: number;
  brandName: string;
  imgUrl: string;
  standardPrice: number;
  discountedPrice: number;
  discountRate: number;
  isSwungDash: boolean;
  baseOrdQty: number;
  freeAwardQty: number;
  isBeautyPoint: boolean;
  isLike: boolean;
  reviewCount: number;
  reviewAverage: number;
  clickUrl?: string;
}

// API 반환 값
// 테스트
export interface ITest {
  title: string;
  order: number;
  img: string;
  subTitle: string;
  products: IProduct[];
}
